# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [4]:
import numpy as np
import itertools


def permutations(dim):
    """
    The function create list of all posible
    permutations of matrix size a.
    """
    c=''
    for i in range(1,dim+1):
        c+=str(i)
    t = list(itertools.permutations(c, dim))
    return t

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def multiply(dim,g):
    """
    The function calculates multiplication
    of every g values in list
    """
    list1=[]
    s=1
    for i in permutations(g):
        for j in range (0, g):
            ((-1)**((int(i[j])-1)+j))*(n[j][int(i[j])-1])
            list1.append(((-1)**((int(i[j])-1)+j))*(n[j][int(i[j])-1]))
    z = 0
    w = g
    list2=[]
    while w<=len(list1):
        for i in range(z, w):
            s *= list1[i]
        list2.append(s)
        z+=g
        w+=g
        s=1
    return list2

def sum(list):
    """
    The function calculates
    sum of values in list
    """
    sum=0
    for i in range(0, len(list)):
        sum += list[i]
    return sum


g=int(input('Please enter dimension of matrix: '))
if g>0:
    n=random_matrix(g)
    u=permutations(g)
    p=multiply(n,g)
    s=sum(p)

    print("Matrix: \n", n)
    print("Permutations: ", u)
    print("Multiply: ", p)
    print("Determinant of matrix: ", s)


Matrix: 
 [[0 5 2]
 [5 2 8]
 [8 4 1]]
Permutations:  [('1', '2', '3'), ('1', '3', '2'), ('2', '1', '3'), ('2', '3', '1'), ('3', '1', '2'), ('3', '2', '1')]
Multiply:  [0, 0, 25, 320, 40, 32]
Determinant of matrix:  417
